name: 'Taher '
favicon: null
layout_spectrum: 0.6131232774350792
typography_spectrum: 0.5529547012411058
title: 'Professional House Cleaning '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.82108866260387
  lightness: 0.14229282387532294
  saturation: 0.6822939212433994
  rhythmicContrast: 0.5744866945315152
purpose: []
